version: "3.7"

services:
  apache2:
    image: httpd:latest
    restart: always
    ports:
    - "80:8080"

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE lenchuk
      MYSQL_USER lenchuk
      MYSQL_PASSWORD userpassword
      MYSQL_ROOT_PASSWORD rootpassword
    restart: always
    ports:
    - "3306:3306"
