Vagrant.configure("2") do |config|

  config.vm.define "ubn" do |ubn|
    ubn.vm.box = "ubuntu/bionic64"
   ubn.vm.provision "shell",
   inline:
   "apt-get update
   apt-get install -y apache2
   mkdir 015 "
ubn.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "ceos" do |ceos|
    ceos.vm.box = "centos/7"
  end
end
